
package pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "businessErrorFault", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0")
public class BusinessErrorFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BusinessErrorFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BusinessErrorFault_Exception(String message, BusinessErrorFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BusinessErrorFault_Exception(String message, BusinessErrorFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.BusinessErrorFault
     */
    public BusinessErrorFault getFaultInfo() {
        return faultInfo;
    }

}
