
package pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentHandlingPort", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    pl.gov.mf.schematy.sisc.wschannel._2014._01_v2_0.ObjectFactory.class,
    pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.ObjectFactory.class
})
public interface DocumentHandlingPort {


    /**
     * 
     * @param acceptDocumentRequest
     * @return
     *     returns pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.AcceptDocumentResponse
     * @throws TechErrorFault_Exception
     * @throws BusinessErrorFault_Exception
     */
    @WebMethod(operationName = "AcceptDocument", action = "AcceptDocument")
    @WebResult(name = "AcceptDocumentResponse", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "AcceptDocumentResponse")
    public AcceptDocumentResponse acceptDocument(
        @WebParam(name = "AcceptDocumentRequest", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "AcceptDocumentRequest")
        AcceptDocumentRequest acceptDocumentRequest)
        throws BusinessErrorFault_Exception, TechErrorFault_Exception
    ;

    /**
     * 
     * @param getNextDocumentRequest
     * @return
     *     returns pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.GetNextDocumentResponse
     * @throws TechErrorFault_Exception
     * @throws BusinessErrorFault_Exception
     */
    @WebMethod(operationName = "GetNextDocument", action = "GetNextDocument")
    @WebResult(name = "GetNextDocumentResponse", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetNextDocumentResponse")
    public GetNextDocumentResponse getNextDocument(
        @WebParam(name = "GetNextDocumentRequest", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetNextDocumentRequest")
        Object getNextDocumentRequest)
        throws BusinessErrorFault_Exception, TechErrorFault_Exception
    ;

    /**
     * 
     * @param getNextDocumentSiscRequest
     * @return
     *     returns pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.GetNextDocumentResponse
     * @throws TechErrorFault_Exception
     * @throws BusinessErrorFault_Exception
     */
    @WebMethod(operationName = "GetNextDocumentSisc", action = "GetNextDocumentSisc")
    @WebResult(name = "GetNextDocumentResponse", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetNextDocumentResponse")
    public GetNextDocumentResponse getNextDocumentSisc(
        @WebParam(name = "GetNextDocumentSiscRequest", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetNextDocumentSiscRequest")
        GetNextDocumentSiscRequest getNextDocumentSiscRequest)
        throws BusinessErrorFault_Exception, TechErrorFault_Exception
    ;

    /**
     * 
     * @param getDocumentsRequest
     * @return
     *     returns pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0.GetDocumentsResponse
     * @throws TechErrorFault_Exception
     * @throws BusinessErrorFault_Exception
     */
    @WebMethod(operationName = "GetDocuments", action = "GetNextDocumentSisc")
    @WebResult(name = "GetDocumentsResponse", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetDocumentsResponse")
    public GetDocumentsResponse getDocuments(
        @WebParam(name = "GetDocumentsRequest", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", partName = "GetDocumentsRequest")
        GetDocumentsRequest getDocumentsRequest)
        throws BusinessErrorFault_Exception, TechErrorFault_Exception
    ;

}
