
package pl.gov.mf.uslugibiznesowe.wspull.usluga._2014._01_v2_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentHandlingSvc", targetNamespace = "http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", wsdlLocation = "file:/C:/Users/KamilM/Documents/workspace-sts-3.8.4.RELEASE/PUESC/ws/WS_PULL.wsdl")
public class DocumentHandlingSvc
    extends Service
{

    private final static URL DOCUMENTHANDLINGSVC_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTHANDLINGSVC_EXCEPTION;
    private final static QName DOCUMENTHANDLINGSVC_QNAME = new QName("http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", "DocumentHandlingSvc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/KamilM/Documents/workspace-sts-3.8.4.RELEASE/PUESC/ws/WS_PULL.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTHANDLINGSVC_WSDL_LOCATION = url;
        DOCUMENTHANDLINGSVC_EXCEPTION = e;
    }

    public DocumentHandlingSvc() {
        super(__getWsdlLocation(), DOCUMENTHANDLINGSVC_QNAME);
    }

    public DocumentHandlingSvc(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTHANDLINGSVC_QNAME, features);
    }

    public DocumentHandlingSvc(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTHANDLINGSVC_QNAME);
    }

    public DocumentHandlingSvc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTHANDLINGSVC_QNAME, features);
    }

    public DocumentHandlingSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentHandlingSvc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentHandlingPort
     */
    @WebEndpoint(name = "DocumentHandlingPort")
    public DocumentHandlingPort getDocumentHandlingPort() {
        return super.getPort(new QName("http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", "DocumentHandlingPort"), DocumentHandlingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentHandlingPort
     */
    @WebEndpoint(name = "DocumentHandlingPort")
    public DocumentHandlingPort getDocumentHandlingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mf.gov.pl/uslugiBiznesowe/WsPull/Usluga/2014/01_v2_0", "DocumentHandlingPort"), DocumentHandlingPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTHANDLINGSVC_EXCEPTION!= null) {
            throw DOCUMENTHANDLINGSVC_EXCEPTION;
        }
        return DOCUMENTHANDLINGSVC_WSDL_LOCATION;
    }

}
